version: 2

before:
  hooks:
    - go mod tidy -go=1.22
    - go generate ./...

builds:
  - env:
      - >-
        {{- if eq .Os "darwin" }}
        CGO_ENABLED=1
        {{- else }}
        CGO_ENABLED=0
        {{- end }}

    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - src: deploy/systemd/git-age-keyring-agent.service
        dst: systemd/git-age-keyring-agent.service
      - src: deploy/systemd/git-age-keyring-agent.socket
        dst: systemd/git-age-keyring-agent.socket

sboms:
  - artifacts: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: git-age-keyring-agent
    homepage: https://github.com/prskr/git-age-keyring-agent
    maintainer: Peter Kurfer <peter.kurfer@gmail.com>
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/git-age-keyring-agent/LICENSE
      - src: deploy/systemd/git-age-keyring-agent.service
        dst: /usr/lib/systemd/system/git-age-keyring-agent.service
        packager: rpm
      - src: deploy/systemd/git-age-keyring-agent.socket
        dst: /usr/lib/systemd/system/git-age-keyring-agent.socket
        packager: rpm
      - src: deploy/systemd/git-age-keyring-agent.service
        dst: /lib/systemd/system/git-age-keyring-agent.service
        packager: deb
      - src: deploy/systemd/git-age-keyring-agent.socket
        dst: /lib/systemd/system/git-age-keyring-agent.socket
        packager: deb

brews:
  - name: git-age-keyring-agent
    homepage: https://github.com/prskr/git-age-keyring-agent
    description: |
      git-age agent to store and load identities from your OS' keyring
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update {{ .ProjectName }} to version {{ .Tag }}"
    skip_upload: auto
    directory: Formula
    service: |
      run [opt_bin/"git-age-keyring-agent", "serve"]
      keep_alive true
    test: |
      system "#{bin}/git-age-keyring-agent --help"
    repository:
      owner: prskr
      name: homebrew-the-prancing-package
      token: "{{ .Env.GH_TAP_PAT }}"
      pull_request:
        enabled: true

aurs:
  - name: git-age-keyring-agent-bin
    homepage: https://github.com/prskr/git-age-keyring-agent
    description: |
      git-age-keyring-agent is an agent for git-age to store keys in the OS keychain
    maintainers:
      - "Peter Kurfer <peter.kurfer@gmail.com>"
    contributors:
      - "Peter Kurfer <peter.kurfer@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/git-age-keyring-agent-bin.git"
    provides:
      - git-age-keyring-agent
    optdepends:
      - git
      - git-age-bin
    package: |-
      # bin
      install -Dm755 "./git-age-keyring-agent" "${pkgdir}/usr/bin/git-age-keyring-agent"

      # service
      install -Dm644 "./systemd/git-age-keyring-agent.service" "${pkgdir}/usr/lib/systemd/system/git-age-keyring-agent.service"
      install -Dm644 "./systemd/git-age-keyring-agent.socket" "${pkgdir}/usr/lib/systemd/system/git-age-keyring-agent.socket"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/git-age-keyring-agent/LICENSE"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: 'chore: update to {{ .Tag }}'
