[hooks]

# git hook pre commit
pre-commit = [
    "go mod tidy -go=1.22",
    "husky lint-staged",
    "golangci-lint run",
]

# git hook commit msg
commit-msg = [
    "husky lint-commit",
]

# list staged files do some pre-process and git add
[lint-staged]
"*.go" = [
    "goimports -l -w",
    "gofumpt -l -w",
]